name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          
      - name: Upload APK
        # تم التحديث هنا من v3 إلى v4
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
